from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
import pymysql

class Ui_MainWindow(object):
    def messagebox(self, title, message):
                mess = QtWidgets.QMessageBox( )
                mess.setWindowTitle( title )
                mess.setText( message )
                mess.setStandardButtons( QtWidgets.QMessageBox.Ok )
                mess.exec_( )

    def update(self):
                email = self.txtEmail.text( )
                password = self.txtNewPassword.text( )
                old = self.txtOldPassword.text( )
                if old != '' and email != '' and password != '':
                        con = pymysql.connect( host="localhost", port=3306, user="root", password="",
                                               db="dumb_can_speak" )
                        cur = con.cursor( )
                        with open( "login-detail.txt", "r" ) as file:  # wirting user id into a file
                                userId = int(file.read( ))
                                print( userId )
                        query = "Select * from users Where id=%s And password=%s"
                        print(password)
                        data = cur.execute( query, (userId, old) )
                        get = cur.fetchone( )
                        print(query)
                        if get!=None :
                                query2 = "UPDATE `users` SET `password`=%s WHERE id=%s"
                                data = cur.execute( query2, (str(password),userId) )
                                print(data)
                                con.commit( )  # finalize the changes
                                # Close the connection
                                cur.close( )
                                con.close( )
                                if (data):
                                        self.messagebox( "Congrats", "Your profile updated" )
                                else:
                                        self.messagebox( "Alert", "Sorry Something went wrong try again" )
                        else:
                                self.messagebox( "Alert", "Password does not match" )
                else:
                        self.messagebox( "Alert", "Please fill all the required fields" )

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 655)
        #set user name
        con = pymysql.connect( host="localhost", port=3306, user="root", password="",
                               db="dumb_can_speak" )
        cur = con.cursor( )
        with open( "login-detail.txt", "r" ) as file:  # wirting user id into a file
                userId = file.read( )
                print( userId );
        query = "Select * from users Where id=%s "
        data = cur.execute( query, (userId) )
        user = cur.fetchone( )
        #end
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG = QtWidgets.QGraphicsView(self.centralwidget)
        self.BG.setGeometry(QtCore.QRect(0, -20, 1080, 640))
        self.BG.setObjectName("BG")
        self.TopMenuBar = QtWidgets.QGraphicsView(self.centralwidget)
        self.TopMenuBar.setGeometry(QtCore.QRect(0, 0, 1071, 51))
        self.TopMenuBar.setStyleSheet("background-color: #000000;")
        self.TopMenuBar.setObjectName("TopMenuBar")
        self.titleProfile = QtWidgets.QLabel(self.centralwidget)
        self.titleProfile.setGeometry(QtCore.QRect(490, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.titleProfile.setFont(font)
        self.titleProfile.setStyleSheet("QLabel* pLabel = new QLabel;\n"
"pLabel->setStyleSheet(\"QLabel { background-color : red; color : blue; }\");")
        self.titleProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.titleProfile.setObjectName("titleProfile")
        self.ButtomMenuBar = QtWidgets.QGraphicsView(self.centralwidget)
        self.ButtomMenuBar.setGeometry(QtCore.QRect(0, 540, 1071, 71))
        self.ButtomMenuBar.setStyleSheet("background-color: #000000;")
        self.ButtomMenuBar.setObjectName("ButtomMenuBar")
        self.DialogBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.DialogBox.setGeometry(QtCore.QRect(330, 60, 421, 471))
        self.DialogBox.setObjectName("DialogBox")
        self.JohnMick = QtWidgets.QLabel(self.centralwidget)
        self.JohnMick.setGeometry(QtCore.QRect(480, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.JohnMick.setFont(font)
        self.JohnMick.setStyleSheet("QLabel* pLabel = new QLabel;\n"
"pLabel->setStyleSheet(\"QLabel { background-color : red; color : blue; }\");")
        self.JohnMick.setAlignment(QtCore.Qt.AlignCenter)
        self.JohnMick.setObjectName("JohnMick")
        self.JohnMick.setText(str(user[1]))
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(360, 290, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("padding-left: 70px;")
        self.txtEmail.setObjectName("txtEmail")
        self.txtEmail.setText( str( user[2] ) )
        self.txtOldPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOldPassword.setGeometry(QtCore.QRect(360, 350, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtOldPassword.setFont(font)
        self.txtOldPassword.setStyleSheet("padding-left: 70px;")
        self.txtOldPassword.setObjectName("txtOldPassword")
        self.txtOldPassword.setEchoMode( QtWidgets.QLineEdit.Password )
        self.txtNewPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNewPassword.setGeometry(QtCore.QRect(360, 410, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtNewPassword.setFont(font)
        self.txtNewPassword.setStyleSheet("padding-left: 70px;")
        self.txtNewPassword.setEchoMode( QtWidgets.QLineEdit.Password )
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.ProfileIcon = QtWidgets.QLabel(self.centralwidget)
        self.ProfileIcon.setGeometry(QtCore.QRect(460, 80, 151, 151))
        self.ProfileIcon.setText("")
        self.ProfileIcon.setPixmap(QtGui.QPixmap("icons/Group 19.png"))
        self.ProfileIcon.setScaledContents(True)
        self.ProfileIcon.setObjectName("ProfileIcon")
        self.EmailIcon_2 = QtWidgets.QLabel(self.centralwidget)
        self.EmailIcon_2.setGeometry(QtCore.QRect(380, 300, 21, 21))
        self.EmailIcon_2.setText("")
        self.EmailIcon_2.setPixmap(QtGui.QPixmap("icons/icons8_secured_letter_50px_2.png"))
        self.EmailIcon_2.setScaledContents(True)
        self.EmailIcon_2.setObjectName("EmailIcon_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 580, 101, 31))
        self.pushButton.setStyleSheet("background:transparent;\n"
"color: #ffffff;")
        self.pushButton.setObjectName("pushButton")
        self.ProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProfileButton.setGeometry(QtCore.QRect(480, 580, 91, 31))
        self.ProfileButton.setStyleSheet("background:transparent;\n"
"color: #ffffff;")
        self.ProfileButton.setObjectName("ProfileButton")
        self.HistoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.HistoryButton.setGeometry(QtCore.QRect(910, 580, 91, 31))
        self.HistoryButton.setStyleSheet("background:transparent;\n"
"color: #ffffff;")
        self.HistoryButton.setObjectName("HistoryButton")
        self.PasswordIcon1 = QtWidgets.QLabel(self.centralwidget)
        self.PasswordIcon1.setGeometry(QtCore.QRect(380, 360, 21, 21))
        self.PasswordIcon1.setText("")
        self.PasswordIcon1.setPixmap(QtGui.QPixmap("icons/icons8_password_50px.png"))
        self.PasswordIcon1.setScaledContents(True)
        self.PasswordIcon1.setObjectName("PasswordIcon1")
        self.PasswordIcon2 = QtWidgets.QLabel(self.centralwidget)
        self.PasswordIcon2.setGeometry(QtCore.QRect(380, 420, 21, 21))
        self.PasswordIcon2.setText("")
        self.PasswordIcon2.setPixmap(QtGui.QPixmap("icons/icons8_password_50px.png"))
        self.PasswordIcon2.setScaledContents(True)
        self.PasswordIcon2.setObjectName("PasswordIcon2")
        self.CameraIconButton = QtWidgets.QLabel(self.centralwidget)
        self.CameraIconButton.setGeometry(QtCore.QRect(160, 550, 41, 41))
        self.CameraIconButton.setText("")
        self.CameraIconButton.setPixmap(QtGui.QPixmap("icons/Camera.png"))
        self.CameraIconButton.setScaledContents(True)
        self.CameraIconButton.setObjectName("CameraIconButton")
        self.ProfileIconButton = QtWidgets.QLabel(self.centralwidget)
        self.ProfileIconButton.setGeometry(QtCore.QRect(510, 550, 31, 31))
        self.ProfileIconButton.setText("")
        self.ProfileIconButton.setPixmap(QtGui.QPixmap("icons/Profile.png"))
        self.ProfileIconButton.setScaledContents(True)
        self.ProfileIconButton.setObjectName("ProfileIconButton")
        self.HistoryIconButton = QtWidgets.QLabel(self.centralwidget)
        self.HistoryIconButton.setGeometry(QtCore.QRect(930, 550, 41, 31))
        self.HistoryIconButton.setText("")
        self.HistoryIconButton.setPixmap(QtGui.QPixmap("icons/History.png"))
        self.HistoryIconButton.setScaledContents(True)
        self.HistoryIconButton.setObjectName("HistoryIconButton")
        self.SaveChangesButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveChangesButton.setGeometry(QtCore.QRect(400, 470, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SaveChangesButton.setFont(font)
        self.SaveChangesButton.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"color: #ffffff;")
        self.SaveChangesButton.setCursor( QCursor( QtCore.Qt.PointingHandCursor ) )
        self.SaveChangesButton.clicked.connect( self.update )
        self.SaveChangesButton.setObjectName("SaveChangesButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleProfile.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Profile</span></p></body></html>"))
        self.txtEmail.setPlaceholderText(_translate("MainWindow", "Johnsmith@gmail.com"))
        self.txtOldPassword.setPlaceholderText(_translate("MainWindow", "Old Password"))
        self.txtNewPassword.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.pushButton.setText(_translate("MainWindow", "Start Video"))
        self.ProfileButton.setText(_translate("MainWindow", "Profile"))
        self.HistoryButton.setText(_translate("MainWindow", "History"))
        self.SaveChangesButton.setText(_translate("MainWindow", "Save Changes"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())